<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 15/09/2017
 * Time: 17:56
 */

namespace Platformservice\Controller;


use Common\Controller\CommonController;
use Thirdwechat\Controller\Wechat\TemplateController;

class TryTestController extends CommonController
{

    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
    }

    public function sendwechatofficialtemplatemsg()
    {
        $params['key_admin'] = I('post.kkk');
        $params['abc']=I('post.aaa');
        if ($params['key_admin'] != 'asldkjflsajfourowejfokjfsd' || $params['abc'] != '99jjod0u3hidiu9ishdaaadjfajdklfal23sdfasdfadfdfafadfad'){
            exit();
        }
        $admininfo = $this->getMerchant('202cb962ac59075b964b07152d234b70');

        $obj = new TemplateController();
        $json = '[
    {
        "touser": "oWm-rt2OE-JtS9JSxlldzjpV1V7M",
        "template_id": "oYCxx8_I129Sb3oDO_k5Uaj5O08BQ_RY3Pii_3wOjdg",
        "url": "",
        "data": {
            "first": {
                "value": "小标题",
                "color": "#173177"
            },
            "keyword1": {
                "value": 110,
                "color": "#173177"
            },
            "keyword2": {
                "value": "oWm-rt-0iAKRtrUyl0zPC28V8m0E",
                "color": "#173177"
            },
            "keyword3": {
                "value": "2016-08-25 09:43:52",
                "color": "#173177"
            },
            "remark": {
                "value": "尊敬的先生，您的请求已经成功！",
                "color": "#173177"
            }
        }
    }]';
        $send = $obj->insideSendMessage(json_decode($json, true), '202cb962ac59075b964b07152d234b70', $admininfo['wechat_appid']);
        if ($send == 200){
            returnjson(array('code'=>200),$this->returnstyle,$this->callback);
        }

    }
}