<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 07/02/2018
 * Time: 11:25
 */

namespace EnterpriseWechat\Controller\App\JsSdk;


use Common\Controller\CommonController;
use EnterpriseWechat\Service\JsSdk\JsSdkService;

class JsSdkController extends CommonController
{
    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
    }

    public function enterpriseWechatJsSdkSign()
    {
        $param['appname'] = I('appname');
        $param['key_admin'] = I('key_admin');
        $param['url'] = I('url');
        if (in_array('', $param)) {
            returnjson(['code'=>1030],$this->returnstyle,$this->callback);
        }
        $data = JsSdkService::jsSdkSign($param['key_admin'], $param['appname'], htmlspecialchars_decode($param['url']));
        returnjson($data,$this->returnstyle,$this->callback);
    }
}