<?php
/**
 * Created by PhpStorm.
 * User: zhangkaifeng
 * Date: 2017/5/17
 * Time: 21:06
 */

namespace Member\Controller;


class UserController extends MemberUserController
{
    private $url;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->url = array(
            '93afca9f6607d7e311dd3888a219d188'=>'http://res.rtmap.com/member/tianheCity/public/register_auto.html?key_admin=93afca9f6607d7e311dd3888a219d188'
        );
    }

    public function checkuser()
    {
        $params['openid'] = I('openid');
        $params['key_admin'] = I('key_admin');
        $params['jumpurl'] = I('jumpurl');
        $params['registerurl'] = I('registerurl');//不做url正确性判断了
        if (in_array('', $params)) {
            $this->assign('errorcode', '参数不全')->display('errorpage.error');
        }else{
            $admininfo = $this->getMerchant($params['key_admin']);
            $userinfo = $this->getUserCardByOpenId($admininfo['pre_table'], $params['openid']);
            if ($userinfo == 2000 || !is_array($userinfo)) {
                header( 'Location:'. $params['registerurl'] );
            }else{
                header( 'Location:'. $params['jumpurl'] );
            }
        }
    }

}