<?php
/**
 * 消息
 */

namespace EnterpriseWechat\Controller\Application;

use EnterpriseWechat\Controller\EnterprisewConfigController;

class ReceiveMessageController extends EnterprisewConfigController
{
    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
    }


    public function Message()
    {
        $corpid = I('get.corpid');
        $suitename = I('suite');
        if ( false == $corpid ) {
            return;
        }else{
            $db = M('enterprise_suite', 'total_');
            $find = $db->where(array('corpid'=>$corpid, 'suite_name'=>$suitename))->find();
            if (false == $find){
                echo 'success';exit;
            }else{
                $token = $find['suite_token'];
                $encodingAesKey = $find['suite_encodingaeskey'];
                $corpId = $find['corpid'];
            }
        }
        $get = I('get.');
        $postData = file_get_contents('php://input');
        //引入微信提供的解密类
        require_once 'Class/Enterprise/WXBizMsgCrypt.php';
        $wxcpt = new \WXBizMsgCrypt($token, $encodingAesKey, $corpId);
        /*
            ------------使用一：验证回调URL---------------
            *企业开启回调模式时，企业号会向验证url发送一个get请求
            假设点击验证时，企业收到类似请求：
            * GET /cgi-bin/wxpush?msg_signature=5c45ff5e21c57e6ad56bac8758b79b1d9ac89fd3&timestamp=1409659589&nonce=263014780&echostr=P9nAzCzyDtyTWESHep1vC5X9xho%2FqYX3Zpb4yKa9SKld1DsH3Iyt3tP3zNdtp%2B4RPcs8TgAE7OaBO%2BFZXvnaqQ%3D%3D
            * HTTP/1.1 Host: qy.weixin.qq.com

            接收到该请求时，企业应
            1.解析出Get请求的参数，包括消息体签名(msg_signature)，时间戳(timestamp)，随机数字串(nonce)以及公众平台推送过来的随机加密字符串(echostr),
            这一步注意作URL解码。
            2.验证消息体签名的正确性
            3. 解密出echostr原文，将原文当作Get请求的response，返回给公众平台
            第2，3步可以用公众平台提供的库函数VerifyURL来实现。

            */
        if (isset($get['echostr']) && '' == $postData){
            $sEchoStr = '';
            $echostr= urldecode($get['echostr']);
            $errCode = $wxcpt->VerifyURL($get['msg_signature'], $get['timestamp'], $get['nonce'], $get['echostr'], $sEchoStr);
            if ($errCode == 0) {
                $echo = $sEchoStr;
            } else {
                $echo = 'success';
            }
            $log['type'] = 'CheckURL';
            $log['get'] = $get;
            $log['postData'] = $postData;
            $log['sEchoStr'] = $sEchoStr;
            $log['echo'] = $echo;
            $log['errCode'] = $errCode;
        }

        /*
            ------------使用示例二：对用户回复的消息解密---------------
            用户回复消息或者点击事件响应时，企业会收到回调消息，此消息是经过公众平台加密之后的密文以post形式发送给企业，密文格式请参考官方文档
            假设企业收到公众平台的回调消息如下：
            POST /cgi-bin/wxpush? msg_signature=477715d11cdb4164915debcba66cb864d751f3e6&timestamp=1409659813&nonce=1372623149 HTTP/1.1
            Host: qy.weixin.qq.com
            Content-Length: 613
            <xml>
            <ToUserName><![CDATA[wx5823bf96d3bd56c7]]></ToUserName><Encrypt><![CDATA[RypEvHKD8QQKFhvQ6QleEB4J58tiPdvo+rtK1I9qca6aM/wvqnLSV5zEPeusUiX5L5X/0lWfrf0QADHHhGd3QczcdCUpj911L3vg3W/sYYvuJTs3TUUkSUXxaccAS0qhxchrRYt66wiSpGLYL42aM6A8dTT+6k4aSknmPj48kzJs8qLjvd4Xgpue06DOdnLxAUHzM6+kDZ+HMZfJYuR+LtwGc2hgf5gsijff0ekUNXZiqATP7PF5mZxZ3Izoun1s4zG4LUMnvw2r+KqCKIw+3IQH03v+BCA9nMELNqbSf6tiWSrXJB3LAVGUcallcrw8V2t9EL4EhzJWrQUax5wLVMNS0+rUPA3k22Ncx4XXZS9o0MBH27Bo6BpNelZpS+/uh9KsNlY6bHCmJU9p8g7m3fVKn28H3KDYA5Pl/T8Z1ptDAVe0lXdQ2YoyyH2uyPIGHBZZIs2pDBS8R07+qN+E7Q==]]></Encrypt>
            <AgentID><![CDATA[218]]></AgentID>
            </xml>

            企业收到post请求之后应该
            1.解析出url上的参数，包括消息体签名(msg_signature)，时间戳(timestamp)以及随机数字串(nonce)
            2.验证消息体签名的正确性。
            3.将post请求的数据进行xml解析，并将<Encrypt>标签的内容进行解密，解密出来的明文即是用户回复消息的明文，明文格式请参考官方文档
            第2，3步可以用公众平台提供的库函数DecryptMsg来实现。
            */
        elseif ('' != $postData && !isset($get['echostr']) ){
            $sMsg = "";  // 解析之后的明文
            $errCode = $wxcpt->DecryptMsg($get['msg_signature'], $get['timestamp'], $get['nonce'], $postData, $sMsg);
            if ($errCode == 0) {
                // 解密成功，sMsg即为xml格式的明文
                // TODO: 对明文的处理
                // For example:
                $xml = new \DOMDocument();
                $xml->loadXML($sMsg);
                $content = $xml->getElementsByTagName('Content')->item(0)->nodeValue;
                $echo = 'success';
            } else {
                $echo = 'success';
            }
            $log['type'] = 'Encrypt';
            $log['get'] = $get;
            $log['postData'] = $postData;
            $log['Msg'] = $sMsg;
            $log['content'] = $content;
            $log['echo'] = $echo;
            $log['errCode'] = $errCode;
        }else{
            $log['echo']='success';
        }
        ob_clean();
        print ($echo);
        $logpath=MODULE_NAME.'-'.CONTROLLER_NAME.'-'.ACTION_NAME;
        $logpath=str_replace('/','-', $logpath);
        $logpath=strtolower($logpath);
        $logpath='enterpriseWechat/'.date('Y-m-d').'/'.$logpath;
        writeOperationLog($log, $logpath);
    }


}


?>

