<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 07/11/2017
 * Time: 16:48
 */

namespace PublicApi\Controller;


use Common\Controller\CommonController;
use MerAdmin\Service\ManageThemeGroupService;
use PublicApi\Service\CouponService;

class ClientController extends CommonController
{
    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub


    }


    /**
     * c端，主题列表
     */
    public function themlist()
    {
        $params['key_admin'] = I('key_admin');
        if (in_array('', $params)) {
            returnjson(array('code'=>1030),$this->returnstyle,$this->callback);
        }
        $admininfo = $this->getMerchant($params['key_admin']);
        $data = ManageThemeGroupService::ThemeList($admininfo);
        returnjson($data,$this->returnstyle,$this->callback);
    }

    /**
     * c端，主题列表
     */
    public function index()
    {
        //通用活动下券批列表接口(3.0:{activityId:18675})
        /*
        $params = array(
            "key_admin"=>"202cb962ac59075b964b07152d234b70",
            'method' =>"getListByAct",
            'api'=>array(
                'activityId'=>"18675",//A01Wtzkce(4.0)
            )
        );
        */


         /*//获取优惠券详情接口(3.0{id:169285})
        $params = array(
            "key_admin"=>"202cb962ac59075b964b07152d234b70",
            'method' =>"getDetailById",
            'api'=>array(
                'couponActivityId'=>"BHfEPB31",
                'id'=>'1333',
            )
        );*/

        //领券接口(不验证)(3.0{couponId,openId,activityId})
        /*
         $params = array(
             "key_admin"=>"202cb962ac59075b964b07152d234b70",
             'method' =>"giveCoupon",
             'api'=>array(
                    "couponId"=>"169285",
                    "openId"=>"11",
                    "activityId"=>"18675",
             )
         );
        */
         /*//领券接口(验证活动)(3.0{couponId,openId,activityId})
        $params = array(
            "key_admin"=>"202cb962ac59075b964b07152d234b70",
            'method' =>"giveCouponCheck",
            'api'=>array(
                "couponId"=>"1333",
                "openId"=>"11",
                "couponActivityId"=>"BHfEPB31",
                "activityId" =>"A01Wtzkce"
            )
        );*/

        /*//C端通用核销接口(没有规则)(3.0 还没有找到)
       $params = array(
           "key_admin"=>"202cb962ac59075b964b07152d234b70",
           'method' =>"couponWriteoff",
           'api'=>array(
               "openId"=>$params['openId'],
                "qrCode"=>$params['qrCode'],
                "writeOffChannel"=>$params['writeOffChannel'],
                "shopId"=>$shopId
           )
       );*/

        //退券接口(没有活动优惠券-未测试)（3.0参数{couponId,couponId,couponId,qrCode}）111
/*
        $params = array(
            "key_admin"=>"202cb962ac59075b964b07152d234b70",
            'method' =>"returnTicket",
            'api'=>array(
                "couponId"=>"169285",
                    "openId"=>"11",
                    "activityId"=>"18675",
                    "qrCode"=>"011516184352930810",
            )
        );
*/
        /*//通用反核销接口(未测试)
        $params = array(
            "key_admin"=>"202cb962ac59075b964b07152d234b70",
            'method' =>"returnWriteOff",
            'api'=>array(
                "openId"=>$params['openId'],
                "qrCode"=>$params['qrCode'],
                "writeOffChannel"=>$params['writeOffChannel'],
                "shopId"=>$shopId
            )
        );*/
        /*//通用反核销接口(未测试)
        $params = array(
            "key_admin"=>"202cb962ac59075b964b07152d234b70",
            'method' =>"giveCouponBatch",
            'api'=>array(
                 *   activityId  String  活动id  是
     *   openId	　　String	用户微信标识	是
     *   type	　　Integer	领取方式:1:微信openId 2:手机号	　是
     *   wxOpenId　　String	手机号领取时需携带openId	否
     *   channelId	Long	渠道ID	否
     *   couponActivityId	String	 券批ID	是
            )
        );*/


        /*查看活动状态*/
        $params = array(
            "key_admin"=>"202cb962ac59075b964b07152d234b70",
            'method' =>"getActivityStatus",
            'api'=>array(
                "activityId"=>"18675",
            )
        );
        $data = CouponService::Index($params);
        echo "<pre>";
        print_r($data);exit;
        returnjson($data,$this->returnstyle,$this->callback);
    }

}