<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 25/12/2017
 * Time: 10:50
 */

namespace EnterpriseWechat\Controller\Open\App;


use Common\Controller\CommonController;
use Common\Service\PublicService;
use Common\Service\RedisService;
use EnterpriseWechat\Service\Open\AppInfoService;

class AppInfoController extends CommonController
{
    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
    }

    public function getRelationShip()
    {
        $param = file_get_contents('php://input');
        $param = json_decode($param, true);
        if (false == $param || !isset($param['appname']) || !isset($param['key_admin']) || !isset($param['sign'])){
            returnjson(['code'=>1030], $this->returnstyle,$this->callback);
        }

        $sign = $param['sign'];
        unset($param['sign']);

        $adminInfo = $this->getMerchant($param['key_admin']);

        $param['sign_key'] = $adminInfo['signkey'];
        if ($sign != sign($param)) {
            returnjson(['code'=>1002], $this->returnstyle,$this->callback);
        }
        $data = AppInfoService::getRelationShip($adminInfo, $param['appname']);
        returnjson($data, $this->returnstyle,$this->callback);
    }
}