<?php
/**
 * Created by PhpStorm.
 * User: jaleel
 * Date: 7/14/16
 * Time: 4:39 PM
 */

namespace ParkApp\Controller;

use Common\Controller\JaleelController;

class ParkPayEnterController extends JaleelController
{
    public $classObj;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $mer_re = $this->getMerchant($this->ukey);
        $default = M('default', $mer_re['pre_table']);
        $re = $default->where(array ('customer_name' => 'parkpayclassname'))->find();
        $this->classObj = new $re['function_name']();
    }

    public function getfree() {
        $this->classObj->getFreeParking();
    }

    public function searchcarno() {
        $this->classObj->searchParkNo();
    }

    public function scorepay() {
        $this->classObj->payByScore();
    }

    public function wxpay() {
        $this->classObj->payByWeiXin();
    }

    public function noticepark() {
        $this->classObj->notifyCarPark();
    }
}