<?php
/**
 * Created by zend studio.
 * User: zhanghang
 * Date: 2017/9/1
 * Time: 10:21
 */

namespace CrmService\Controller\Crmapi;

use Common\Controller\WebserviceController;
use CrmService\Controller\CommonController;
use CrmService\Controller\CrminterfaceController;

class ShouchuangjudaCrmController extends CommonController implements CrminterfaceController
{
    
    public $admininfo;
    public $reqdate;
    public $reqtime;
    public $secret_key;
    public $request_url;
    public $base_key;
    
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->reqdate = date('Ymd');
        $this->reqtime = date('His');
        $this->secret_key = '20170929224137';
        $this->request_url = 'http://218.205.210.10:2180/CRM_VIP_Proxy.asmx?wsdl';
        $this->base_key = '89622015104709087435617163207900';
        
        $this->admininfo=$this->getMerchant($this->ukey);
    }

    /**
     * @deprecated 根据卡号获取会员信息
     * @传入参数   key_admin、sign、card
     *
     */
    public function GetUserinfoByCard()
    {
        $params['vipcode'] = I('card');
        
        $db=M('mem',$this->admininfo['pre_table']);
//         $mem_data = $db->where(array('mobile'=>$params['mobile']))->find();
//         $params['vipcode'] = $mem_data['cardno'];
        
        //         if($params['vipcode'] == ''){
        //             $msg['code']=102;
        //             returnjson($msg,$this->returnstyle,$this->callback);
        //         }
        
        $request = $this->sign_action_header($this->reqdate,$this->reqtime,$params['vipcode'],$this->secret_key);
        
//         $mobile=$this->encode($this->base_key,$params['mobile']);
        $vipcode=$this->encode($this->base_key,$params['vipcode']);
        
        $str = <<<EOT
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetVipInfoByMobileOpenID xmlns="http://www.tech-trans.com.cn/">
      <request>
        <Header>
          <REQDATE>$this->reqdate</REQDATE>
          <REQTIME>$this->reqtime</REQTIME>
          <SIGN>$request</SIGN>
        </Header>
        <Data>
          <vipcode>$vipcode</vipcode>
          <mobile></mobile>
          <openid></openid>
        </Data>
      </request>
    </GetVipInfoByMobileOpenID>
  </soap:Body>
</soap:Envelope>
EOT;
        
        $webservice= new WebserviceController($this->admininfo['pre_table']);
        $client=$webservice->soapClient($this->request_url);
        $result= $webservice->doRequest($str, $this->request_url, 'http://www.tech-trans.com.cn/GetVipInfoByMobileOpenID', $client);
        if($result){
            $data = xml_to_array($result);
            //             print_r($data);die;
            if($data['GetVipInfoByMobileOpenIDResponse']['GetVipInfoByMobileOpenIDResult']['Header']['ERRCODE']){
                $msg['code']=102;
                $msg['msg']=$data['GetVipInfoByMobileOpenIDResponse']['GetVipInfoByMobileOpenIDResult']['Header']['ERRMSG'];
            }else{
                $msg['code']=200;
                $arr = $data['GetVipInfoByMobileOpenIDResponse']['GetVipInfoByMobileOpenIDResult']['DATA']['VIP'];
                $msg['data']['mobile']=$this->decode($arr['xf_telephone'],$this->base_key);
                $msg['data']['cardno']=$params['vipcode'];
                $msg['data']['user']=$arr['xf_surname']?$this->decode($arr['xf_surname'],$this->base_key):'';
                $msg['data']['status']=$arr['xf_active'];
                $msg['data']['getcarddate']=$arr['xf_jointdate'];
                $msg['data']['expirationdate']=$arr['xf_expirydate'];
                $msg['data']['birthday']=$arr['xf_birthdayyyyy']==1?'':$arr['xf_birthdayyyyy'].'-'.$arr['xf_birthdaymm'].'-'.$arr['xf_birthdaydd'];
                $msg['data']['address']=$arr['xf_address1']?$arr['xf_address1']:$arr['xf_address2'];
                $msg['data']['score']=$arr['xf_bonus']?$this->decode($arr['xf_bonus'],$this->base_key):'';
                $msg['data']['xf_issuestore']=$arr['xf_issuestore']?$arr['xf_issuestore']:'';
                
                $save_data['usermember']=$msg['data']['user'];
                $save_data['status']=$msg['data']['status'];
                $save_data['status_description']='';
                $save_data['getcarddate']=$msg['data']['getcarddate'];
                $save_data['expirationdate']=$msg['data']['expirationdate'];//到期时间
                $save_data['birthday']=$msg['data']['birthday'];
                $save_data['phone']=$msg['data']['mobile'];
                $save_data['mobile']=$msg['data']['mobile'];
                $save_data['address']=$msg['data']['address'];
                $save_data['score_num']=$msg['data']['score'];//会员积分
        
                $arr1=$db->where('cardno='.$params['vipcode'])->find();
                if($arr1){
                    $add=$db->where('cardno='.$params['vipcode'])->save($save_data);
                }else{
                    $save_data['cardno']=$msg['data']['cardno'];
                    $add=$db->add($save_data);
                }
        
            }
        }else{
            $msg['code']=104;
        }
        returnjson($msg,$this->returnstyle,$this->callback);
    }

    /**
     * @deprecated 根据手机号获取会员信息
     * @传入参数  key_admin、sign、mobile
     */
    public function GetUserinfoByMobile()
    {
        $params['mobile'] = I('mobile');
        
        $db=M('mem',$this->admininfo['pre_table']);
        $mem_data = $db->where(array('mobile'=>$params['mobile']))->find();
//         $params['vipcode'] = $mem_data['cardno'];

//         if($params['vipcode'] == ''){
//             $msg['code']=102;
//             returnjson($msg,$this->returnstyle,$this->callback);
//         }
        
        $request = $this->sign_action_header($this->reqdate,$this->reqtime,'',$this->secret_key);
        
        $mobile=$this->encode($this->base_key,$params['mobile']);
//         $vipcode=$params['vipcode']?$this->encode($this->base_key,$params['vipcode']):'';
        
        $str = <<<EOT
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetVipInfoByMobileOpenID xmlns="http://www.tech-trans.com.cn/">
      <request>
        <Header>
          <REQDATE>$this->reqdate</REQDATE>
          <REQTIME>$this->reqtime</REQTIME>
          <SIGN>$request</SIGN>
        </Header>
        <Data>
          <vipcode></vipcode>
          <mobile>$mobile</mobile>
          <openid></openid>
        </Data>
      </request>
    </GetVipInfoByMobileOpenID>
  </soap:Body>
</soap:Envelope>        
EOT;
        
        $webservice= new WebserviceController($this->admininfo['pre_table']);
        $client=$webservice->soapClient($this->request_url);
        $result= $webservice->doRequest($str, $this->request_url, 'http://www.tech-trans.com.cn/GetVipInfoByMobileOpenID', $client);
        if($result){
            $data = xml_to_array($result);
//             print_r($data);
            if($data['GetVipInfoByMobileOpenIDResponse']['GetVipInfoByMobileOpenIDResult']['Header']['ERRCODE']){
                $msg['code']=102;
                $msg['msg']=$data['GetVipInfoByMobileOpenIDResponse']['GetVipInfoByMobileOpenIDResult']['Header']['ERRMSG'];
            }else{
                $msg['code']=200;
                $arr = $data['GetVipInfoByMobileOpenIDResponse']['GetVipInfoByMobileOpenIDResult']['DATA']['VIP'];
                $msg['data']['mobile']=$this->decode($arr['xf_telephone'],$this->base_key);
                $msg['data']['cardno']=$this->decode($arr['xf_vipcode'],$this->base_key);
                $msg['data']['user']=$arr['xf_surname']?$this->decode($arr['xf_surname'],$this->base_key):'';
                $msg['data']['status']=$arr['xf_active'];
                $msg['data']['getcarddate']=$arr['xf_jointdate'];
                $msg['data']['expirationdate']=$arr['xf_expirydate'];
                $msg['data']['birthday']=$arr['xf_birthdayyyyy']==1?'':$arr['xf_birthdayyyyy'].'-'.$arr['xf_birthdaymm'].'-'.$arr['xf_birthdaydd'];
                $msg['data']['address']=$arr['xf_address1']?$arr['xf_address1']:$arr['xf_address2'];
                $msg['data']['score']=$arr['xf_bonus']?$this->decode($arr['xf_bonus'],$this->base_key):'';
                $msg['data']['xf_issuestore']=$arr['xf_issuestore']?$arr['xf_issuestore']:'';
                
                $save_data['usermember']=$msg['data']['user'];
                $save_data['status']=$msg['data']['status'];
                $save_data['status_description']='';
                $save_data['getcarddate']=$msg['data']['getcarddate'];
                $save_data['expirationdate']=$msg['data']['expirationdate'];//到期时间
                $save_data['birthday']=$msg['data']['birthday'];
                $save_data['phone']=$msg['data']['mobile'];
                $save_data['mobile']=$msg['data']['mobile'];
                $save_data['address']=$msg['data']['address'];
                $save_data['score_num']=$msg['data']['score'];//会员积分
                $save_data['cardno']=$msg['data']['cardno'];
                
                $arr1=$db->where('cardno='.$msg['data']['cardno'])->find();
                if($arr1){
                    $add=$db->where('cardno='.$msg['data']['cardno'])->save($save_data);
                }else{
                    $add=$db->add($save_data);
                }
                
            }
        }else{
        $msg['code']=104;
        }
        returnjson($msg,$this->returnstyle,$this->callback);   
    }

    /**
     * @deprecated  创建会员
     * @传入参数  key_admin、sign、mobile、sex、idnumber、name
     */
    public function createMember()
    {
        $params['mobile']=I('mobile');//手机号( 密文 )
        $xf_issuestore=I('xf_issuestore');//来源
        $xf_vipcodeprefix=510;//卡号前缀
            
        $request = $this->sign_action_header($this->reqdate,$this->reqtime,$params['mobile'],$this->secret_key);

        //按照规则进行加密
        $mobile=$this->encode($this->base_key,$params['mobile']);
        //加密结束
        //转换XML格式
//         $header = $this->arrayToXml($data);

        $str = <<<EOT
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <VipCreate xmlns="http://www.tech-trans.com.cn/">
      <request>
        <Header>
          <REQDATE>$this->reqdate</REQDATE>
          <REQTIME>$this->reqtime</REQTIME>
          <SIGN>$request</SIGN>
        </Header>
        <Data>
          <vip>
            <mobile>$mobile</mobile>
            <xf_issuestore>$xf_issuestore</xf_issuestore>
            <xf_vipcodeprefix>$xf_vipcodeprefix</xf_vipcodeprefix>
          </vip>
        </Data>
      </request>
    </VipCreate>
  </soap:Body>
</soap:Envelope>
EOT;

        $webservice= new WebserviceController($this->admininfo['pre_table']);
        $client=$webservice->soapClient($this->request_url);
        $result= $webservice->doRequest($str, $this->request_url, 'http://www.tech-trans.com.cn/VipCreate', $client);
        if($result){
            $data = xml_to_array($result);
//             print_r($data);die;
            if($data['VipCreateResponse']['VipCreateResult']['Header']['ERRCODE'] && $data['VipCreateResponse']['VipCreateResult']['Header']['ERRCODE'] != 101){
                $msg['code']=104;
                $msg['msg']=$data['VipCreateResponse']['VipCreateResult']['Header']['ERRMSG'];
            }else{
                $msg['code']=200;
                
                $data['cardno']=$this->decode($data['VipCreateResponse']['VipCreateResult']['DATA']['xf_vipcode'],$this->base_key);
                $data['phone']=$params['mobile'];
                $data['mobile']=$params['mobile'];
                
                $db=M('mem',$this->admininfo['pre_table']);
                $arr1=$db->where('mobile='.$params['mobile'])->find();
                if($arr1){
                    $add=$db->where('mobile='.$params['mobile'])->save($data);
                }else{
                    $add=$db->add($data);
                }
//                 print_r($db->_sql());die;
                $msg['data']['cardno']=$this->decode($data['VipCreateResponse']['VipCreateResult']['DATA']['xf_vipcode'],$this->base_key);
                $msg['data']['mobile']=$params['mobile'];
            }
            
        }else{
            $msg['code']=104;
        }
        returnjson($msg,$this->returnstyle,$this->callback);
    }

    public function sign_action_header($reqdate,$reqtime,$params = '',$secret_key){
        $str = $reqdate.$reqtime.$params.$secret_key;
        return MD5($str);
    }
    
    //按照AEC加密方式进行加密
    public function encode( $key, $str ){
        $iv = mcrypt_create_iv(mcrypt_get_iv_size(MCRYPT_RIJNDAEL_128,MCRYPT_MODE_ECB),MCRYPT_RAND);
        return base64_encode(mcrypt_encrypt(MCRYPT_RIJNDAEL_128, $key, $str, MCRYPT_MODE_ECB, $iv));
    }
    
    //按照AEC加密方式进行解密
    public function decode( $str, $key ){
//         echo $str;die;
        $str = base64_decode($str);
        $iv = mcrypt_create_iv(mcrypt_get_iv_size(MCRYPT_RIJNDAEL_128,MCRYPT_MODE_ECB),MCRYPT_RAND);  
        $decrypted = mcrypt_decrypt(MCRYPT_RIJNDAEL_128, $key, $str, MCRYPT_MODE_ECB, $iv);  
        $decrypted = rtrim($decrypted);
        return $decrypted;
    }
    
    
    /**
     * @deprecated  修改会员信息
     * @传入参数  key_admin、sign、mobile、sex、idnumber、name、cardno
     */
    public function editMember()
    {
        
    }

    /**
     * @deprecated  积分扣除
     * @传入参数  key_admin、sign、cardno、scoreno、why
     */
    public function cutScore()
    {
        //JFG001
        $params['Vipcode'] = I('cardno');
        $params['bonus'] = I('scoreno');
        $params['remark'] = I('why');
        $params['reasoncode'] = I('reasoncode');
        
        $params['bonus'] = abs($params['bonus'])*-1;
        $request = $this->sign_action_header($this->reqdate,$this->reqtime,$params['bonus'],$this->secret_key);

        $params['bonus']=$this->encode($this->base_key,$params['bonus']);
        $params['Vipcode']=$this->encode($this->base_key,$params['Vipcode']);
        $expdate = date('Y',time()) + 20 . '-' . date('m-d');
        $msg = $this->score_action($request,$params['Vipcode'],$params['bonus'],$params['remark'],$params['reasoncode'],$expdate,1);
        
        returnjson($msg,$this->returnstyle,$this->callback);
    }

    //积分调整公共处理
    public function score_action($sign,$vipcode,$bonus,$remark,$reasoncode,$expdate,$status,$code = ''){
        
        $str = <<<EOT
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <BonusChange xmlns="http://www.tech-trans.com.cn/">
      <request>
        <Header>
          <REQDATE>$this->reqdate</REQDATE>
          <REQTIME>$this->reqtime</REQTIME>
          <SIGN>$sign</SIGN>
        </Header>
        <Data>
          <vipcode>$vipcode</vipcode>
          <openid></openid>
          <expdate>$expdate</expdate>
          <bonus>$bonus</bonus>
          <reasoncode>$reasoncode</reasoncode>
          <effectdate></effectdate>
          <remark>$remark</remark>
        </Data>
      </request>
    </BonusChange>
  </soap:Body>
</soap:Envelope> 
EOT;
//         echo $str;
        $webservice= new WebserviceController($this->admininfo['pre_table']);
        $client=$webservice->soapClient($this->request_url);
        $result= $webservice->doRequest($str, $this->request_url, 'http://www.tech-trans.com.cn/BonusChange', $client);
        if($result){
            $data = xml_to_array($result);
            if($data['BonusChangeResponse']['BonusChangeResult']['Header']['ERRCODE']){
                $msg['code']=104;
                $msg['msg']=$data['BonusChangeResponse']['BonusChangeResult']['Header']['ERRMSG'];
            }else{
                $msg['code']=200;
//                 print_r($data);die;
                $arr = $data['BonusChangeResponse']['BonusChangeResult']['DATA'];
                $save_data['cardno']=$this->decode($vipcode,$this->base_key);
                $save_data['scorenumber']=abs($this->decode($bonus,$this->base_key));
                $save_data['why']=$remark;
                $save_data['scorecode']=$code?$code:date('Y-m-d');
                $save_data['cutadd']=$status;
                
                $db=M('score_record',$this->admininfo['pre_table']);
                $add=$db->add($save_data);
                
                $msg['data']['cardno']=$this->decode($vipcode,$this->base_key);
                $msg['data']['scorenumber']=$this->decode($bonus,$this->base_key);
                $msg['data']['why']=$remark;
                $msg['data']['scorecode']=$this->decode($arr['currentbonus'], $this->base_key);
            }
        }else{
            $msg['code']=104;
        }
        return $msg;
    }
    
    //获取积分原由所有列表
    public function  reasoncode_list(){
        $str = <<<EOT
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetBasicInfo xmlns="http://www.tech-trans.com.cn/" />
  </soap:Body>
</soap:Envelope>
EOT;
        $webservice= new WebserviceController($this->admininfo['pre_table']);
        $client=$webservice->soapClient($this->request_url);
        $result= $webservice->doRequest($str, $this->request_url, 'http://www.tech-trans.com.cn/GetBasicInfo', $client);
        $data = xml_to_array($result);
        returnjson(array('code'=>200,'data'=>$data['GetBasicInfoResponse']['GetBasicInfoResult']['DATA']['adjuest_cause']),$this->returnstyle,$this->callback);
    }
    
    
    /**
     * @deprecated  积分添加
     * @传入参数  key_admin、sign、cardno、scoreno、scorecode、why、membername
     */
    public function addintegral()
    {
        //JFG001
        $params['Vipcode'] = I('cardno');
        $params['bonus'] = I('scoreno');
        $params['remark'] = I('why');
        $params['reasoncode'] = I('reasoncode');
        $params['scorecode'] = I('scorecode');
        $params['membername'] = I('membername');
        
        $params['bonus'] = abs($params['bonus']);
        $request = $this->sign_action_header($this->reqdate,$this->reqtime,$params['bonus'],$this->secret_key);
        
        $params['bonus']=$this->encode($this->base_key,$params['bonus']);
        $params['Vipcode']=$this->encode($this->base_key,$params['Vipcode']);
        $expdate = date('Y',time()) + 20 . '-' . date('m-d');
        $msg = $this->score_action($request,$params['Vipcode'],$params['bonus'],$params['remark'],$params['reasoncode'],$expdate,2,$params['scorecode']);
        
        returnjson($msg,$this->returnstyle,$this->callback);
    }

    /**
     * @deprecated 用户积分详细列表
     */
    public function scorelist()
    {
        
    }

    /**
     * @deprecated 欧亚卖场
     * @传入参数 key_admin、sign 、skt、Jlbh、md
     */
    public function billInfo()
    {

    }


    private function changeScore(array $params, $cardno, $remark, $cutadd)
    {
        
    }

    public function GetUserinfoByOpenid(){

    }
    
    
    /**
     * 解绑
     */
    public function UnBind(){}
}

