<?php
/**
 *
 * Created by PhpStorm.
 * User: zhang
 * Date: 07/12/2017
 * Time: 10:41
 */

namespace EnterpriseWechat\Controller\App\Callback;


use Common\Controller\CommonController;
use EnterpriseWechat\Service\EnterpriseWechatCommonService;
use EnterpriseWechat\Service\Message\MessageCommonService;
use EnterpriseWechat\Service\MsgcryptService;

class InstructionController extends CommonController
{

    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * 指令回调URL配置
     * https://work.weixin.qq.com/api/doc#10970所搜指令回调URL
     * 因微信文档要求的URL内没有规定是否可以用$CORPID表示，所以此功能的设计逻辑为将应用信息存入数据表，并读入缓存，每一个应用另起一个别名，别名是本方法内的一个接收参数，以此区分应用，避免每个应用写一个方法：
     * 例：https://backend.rtmap.com/EnterpriseWechat/App/Callback/Instruction/instructionCallback/appname/test1，appname的值为应用的别名，需存入数据库
     */
    public function instructionCallback()
    {
        $arr['where'] = 'instruction';
        $arr['get']=$_GET;
        $arr['post']=$_POST;
        $arr['file']=file_get_contents('php://input');
        writeOperationLog($arr, 'enterpriseinstruction');
        $get = I('param.');
        //如果是判断URL准确性的请求
        if (isset($get['echostr'])){
            $decrypt = MsgcryptService::CallbackValid(urldecode($get['msg_signature']), urldecode($get['timestamp']), urldecode($get['nonce']), $get['echostr'], urldecode($get['appname']));
            if ($decrypt !== false){
                echo $decrypt;
            }else{
                echostr('success');//其实回复success是错误的，必须要回复echostr的解密内容
            }
        }else{
            //解密xml内容
            $decrypt = MsgcryptService::receiveEventMessageDecrypt($arr['file'], $_GET['appname'], $_GET['msg_signature'], $_GET['timestamp'], $_GET['nonce'], false, $arr['where'], $_GET);
            if ($decrypt === false){
                echo 'success';
            }

            $appInfo = EnterpriseWechatCommonService::getAppInfoByName($_GET['appname']);
            $data = MessageCommonService::callbackMessageHandle($decrypt, $appInfo);
            if (false !== $data){
                echo $data;
            }else{
                echo 'success';
            }





        }




    }







}