<?php
/**
 * Created by PhpStorm.
 * User: zhangkaifeng
 * Date: 2017/5/2
 * Time: 17:50
 * 微信第三方平台对外的一些接口
 */

namespace Thirdwechat\Controller\Wechat;



class OpenWechatApiController extends WechatcommonController
{

//    public function _initialize()
//    {
//        parent::__initialize(); // TODO: Change the autogenerated stub
//    }




    public function setRedPackMessage()
    {
        if (!$this->ukey) {
            returnjson(array('code'=>'1030'),$this->returnstyle,$this->callback);
        }

        $admininfo = $this->getMerchant($this->ukey);
        if ($admininfo['wechat_appid']) {
            $this->redis->set('wechat:issendrequest:'.$admininfo['wechat_appid'], 'yes');
            $get = $this->redis->get('wechat:issendrequest:'.$admininfo['wechat_appid']);
            if ( $get == 'yes') {
                returnjson(array('code'=>'200'),$this->returnstyle,$this->callback);
            }else{
                returnjson(array('code'=>'104'),$this->returnstyle,$this->callback);
            }
        }else{
            returnjson(array('code'=>'104', 'data'=>'appid为空，联系相关人员补全场馆信息'),$this->returnstyle,$this->callback);
        }
    }
}