runtime! debian.vim
if has("syntax")
  syntax on
endif
set showcmd             " Show (partial) command in status line.
"set showmatch          " Show matching brackets.
"set ignorecase         " Do case insensitive matching
"set smartcase          " Do smart case matching
set incsearch           " Incremental search
set autowrite           " Automatically save before commands like :next and :make
set cindent
set softtabstop=4
set shiftwidth=4
set tabstop=4
set hlsearch
set tags=tags;/
filetype indent on
map <C-n> :nohl<cr>
set nu
let g:neocomplcache_enable_at_startup = 1
func SetEncodingUTF8()
     :set enc=utf-8
     :set tenc=utf-8
     :e
endfunc
map  <F11>      :call SetEncodingUTF8() <CR>
imap <F11>      <ESC>:call SetEncodingUTF8() <CR>
:inoremap ( ()<ESC>i
		:inoremap ) <c-r>=ClosePair(')')<CR>
:inoremap { {}<ESC>i
	:inoremap } <c-r>=ClosePair('}')<CR>
	:inoremap [ []<ESC>i
	:inoremap ] <c-r>=ClosePair(']')<CR>
	:inoremap < <><ESC>i
	:inoremap > <c-r>=ClosePair('>')<CR>

	function ClosePair(char)
	     if getline('.')[col('.') - 1] == a:char
	          return "\<Right>"
		       else
		            return a:char
			           endif
				   endf

				   function! PhpCheckSyntax()
	" Check php syntax
	setlocal makeprg=\php\ -l\ -n\ -d\ html_errors=off\ %
	 " Set shellpipe setlocal shellpipe=>
	  " Use error format for parsing PHP error output
	  setlocal errorformat=%m\ in\ %f\ on\ line\ %l
	  make %endfunction
	  " Perform :PhpCheckSyntax()map <F6> :call PhpCheckSyntax()<CR>
	  " imap <F6> <ESC>:call PhpCheckSyntax()<CR>
	  endf
	  autocmd BufWritePost *.php :call PhpCheckSyntax()
:set fileformats=unix,dos
:set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
":e ++ff=unix
":%s/[^[:print:]]$//g
"
"

""""""""""""""""""""""""""""""
" Tag list (ctags)
""""""""""""""""""""""""""""""
let Tlist_Show_One_File = 1            "不同时显示多个文件的tag，只显示当前文件的
let Tlist_Exit_OnlyWindow = 1          "如果taglist窗口是最后一个窗口，则退出vim
let Tlist_Use_Right_Window = 0         "在右侧窗口中显示taglist窗口
nnoremap <silent> <F8> :TlistToggle<CR> 
"解决右键复制问题
"let Tlist_Auto_Open = 1    "自动打开taglist



"minibufExplorer插件
"set mouse=v  " always use mouse
"let g:miniBufExplMapWindowNavVim = 0   
"let g:miniBufExplMapWindowNavArrows = 0   
"let g:miniBufExplMapCTabSwitchBufs = 0   
"let g:miniBufExplModSelTarget = 0  
"let g:miniBufExplMoreThanOne=0  


"winmanager插件
let g:NERDTree_title="[NERDTree]"  
let g:winManagerWindowLayout="NERDTree|TagList"  
  
function! NERDTree_Start()  
	exec 'NERDTree'  
endfunction  
  
function! NERDTree_IsValid()  
	return 1  
endfunction  
  
nmap wm :WMToggle<Esc>:set mouse=a<CR> 
nmap <silent> <F2> <Esc>:set mouse=<CR> 
nmap <silent> <F3> <Esc>:set mouse=a<CR> 
nmap <silent> <F9> <Esc>:BufExplorer<CR> 
nmap <silent> <F10> <Esc>:bp<CR> 
nmap <silent> <F12> <Esc>:bn<CR> 
