<?php
/**
 * 美味不用等排队相关，只有排队
 * Created by PhpStorm.
 * User: zhangkaifeng
 * Date: 2017/6/13
 * Time: 11:22
 */

namespace Mwee\Controller;


use Common\Controller\CommonController;

class MweeQueueController extends CommonController
{
    private $mweeobj;
    private $admininfo;
    private $mweeinfo;
    private $apiurl = 'http://api.mwee.cn/api/queue';
    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
        $this->admininfo = $this->getMerchant($this->ukey);
        $this->mweeobj= new CommonMweeController();
        $this->mweeinfo = $this->mweeobj->getShopMweeSecret($this->admininfo);
    }


    /**
     * 回调信息
     */
    public function hooks()
    {}


    /**
     * 商家总排队信息
     */
    public function shopQueue()
    {
        $sid = (int)I('sid');
        $url =$this->apiurl . '/detail/';
        $array = array(
            'token'=>$this->mweeinfo['apptoken'],
            'sid'=>$sid,
            't'=>time()
        );
        $sn = $this->mweeobj->CreateSn($this->admininfo, $array);
        $array['sn'] = $sn;
        $queue = http($url, $array, 'POST');
        if (is_json($queue)){
            $queuearr = json_decode($queue, true);
            if (0 === $queuearr['errno']){
                $msg['code'] = 200;
                $msg['data'] = $queuearr['result'];
            }else{
                $msg['code'] = 101;
                $msg['data'] = $queuearr;
            }
        }else{
            $msg['code'] = 101;
        }
        returnjson($msg, $this->returnstyle, $this->callback);
    }

    /**
     * 批量查询商家排队信息
     */
    public function shopsQueue()
    {}


    /**
     * 用户点击排队（或者说是取号）
     */
    public function reqQueue()
    {
        $params['key_admin'] = I('key_admin');
        $params['sid'] = (int)I('sid');
        $params['mobile'] = I('mobile');
        $params['people'] = (int)I('people');
        $params['uid']  = $this->userucid;
        $admininfo = $this->getMerchant($params['key_admin']);

        if (in_array('', $params)){
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }
        $orderid = date('YmdHis') . rand(100000, 999999) . rand(100000, 999999);
        $url =$this->apiurl . '/req/';
        $array = array(
            'token'=>$this->mweeinfo['apptoken'],
            'sid'=>$params['sid'],
            'orderid'=>$orderid,
            'm'=>$params['mobile'],
            'p'=>$params['people'],
            't'=>time()
        );
        $sn = $this->mweeobj->CreateSn($this->admininfo, $array);
        $array['sn'] = $sn;
        $queue = http($url, $array, 'POST');
        if (is_json($queue)){
            $queuearr = json_decode($queue, true);
            if (0 === $queuearr['errno']){//如果请求成功，将订单存入数据库
                $data = array(
                    'sid'=>$params['sid'],
                    'userucid'=>$params['uid'],
                    'orderid'=>$orderid,
                    'mobile'=>$params['mobile'],
                    'type'=>0,//0是普通对列，1和2是VIP队列
                    'people'=>$params['people'],
                    'serialid'=>$queuearr['result']['serialid']
                );
                $db = M('mwee', $admininfo['pre_table']);
                $add = $db->add($data);
                $msg['code'] = 200;
                $msg['data'] = $queuearr['result'];
            }else{
                $msg['code'] = 1082;
                $msg['data'] = $queuearr;
                $msg['msg'] = $queuearr['errmsg'];
            }
        }else{
            $msg['code'] = 101;
        }
        returnjson($msg, $this->returnstyle, $this->callback);
    }

    /**
     * 我的排队信息
     */
    public function myQueue()
    {
        $params['key_admin'] = I('key_admin');
        $params['uid'] = $this->userucid;
        $admininfo = $this->getMerchant($params['key_admin']);

        if (in_array('', $params)){
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }
        $array = array(
            'token'=>$this->mweeinfo['apptoken'],
            't'=>time()
        );
        $params['sid'] = (int)I('sid');
        $params['mobile'] = I('mobile');

        $params['orderid'] = (int)I('orderid');
        $params['serialid'] = I('serialid');
        
        if (empty($params['orderid']) || empty($params['serialid'])) {
            if (!empty($params['sid'])) {//如果传了商铺的id，则查询用户在这个商铺的一条信息
                $db = M('mwee', $admininfo['pre_table']);
                $find = $db->where(array('sid'=>$params['sid'],'userucid'=>$params['uid']))->order('id desc')->find();
                if ($find) {
                    $array['orderid'] = $find['orderid'];
                    $array['serialid'] = $find['serialid'];
                }else{
                    returnjson(array('code'=>102), $this->returnstyle, $this->callback);
                }
            }
        }else{
            $array['orderid'] = $params['orderid'];
            $array['serialid'] = $params['serialid'];
        }



        //如果没有店铺id
        if (!isset($array['orderid'])){
            $array['m'] = $params['mobile'];

        }

        $url =$this->apiurl . '/user/';

        $sn = $this->mweeobj->CreateSn($this->admininfo, $array);
        $array['sn'] = $sn;
        $queue = http($url, $array, 'POST');
        if (is_json($queue)){
            $queuearr = json_decode($queue, true);
            if (0 === $queuearr['errno']){
                $msg['code'] = 200;
                $msg['data'] = $queuearr['result'];
            }else{
                $msg['code'] = 101;
                $msg['data'] = $queuearr;
            }
        }else{
            $msg['code'] = 101;
        }
        returnjson($msg, $this->returnstyle, $this->callback);
    }


    /**
     * 用户取消排队接口
     */
    public function cancelQuue()
    {
        $params['orderid'] = I('orderid');
        $params['serialid']= I('serialid');
        if (in_array('', $params)){
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }

        $url =$this->apiurl . '/cancel/';
        $array = array(
            'token'=>$this->mweeinfo['apptoken'],
            'orderid'=>$params['orderid'],
            'serialid'=>$params['serialid'],
            't'=>time()
        );
        $sn = $this->mweeobj->CreateSn($this->admininfo, $array);
        $array['sn'] = $sn;
        $queue = http($url, $array, 'POST');
        if (is_json($queue)){
            $queuearr = json_decode($queue, true);
            if (0 === $queuearr['errno']){
                $msg['code'] = 200;
                $msg['data'] = $queuearr['result'];
            }else{
                $msg['code'] = 1082;
                $msg['data'] = $queuearr;
                $msg['msg'] = $queuearr['errmsg'];
            }
        }else{
            $msg['code'] = 101;
        }
        returnjson($msg, $this->returnstyle, $this->callback);
    }


    /**
     * 附近排队接口
     */
    public function nearQueue()
    {}







}