<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 28/12/2017
 * Time: 11:08
 */

namespace EnterpriseWechat\Controller\App\Menu;


use Common\Controller\CommonController;
use EnterpriseWechat\Service\Menu\MenuService;
use EnterpriseWechat\Service\Open\AppInfoService;

class MenuController extends CommonController
{
    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * 设置菜单
     */
    public function setMenu()
    {
        $params['key_admin'] = I('get.key_admin');
        $params['appname'] = I('get.appname');
        $params['content'] = file_get_contents('php://input');
        if (in_array(false, $params)) {
            returnjson(['code'=>1030],$this->returnstyle,$this->callback);
        }

        $adminInfo = $this->getMerchant($params['key_admin']);

        $authInfo = AppInfoService::getRelationShip($adminInfo, $params['appname']);
        if (!is_array($authInfo) || $authInfo['data']['auth_id'] == false){
            returnjson($authInfo, $this->returnstyle, $this->callback);
        }

        $data = MenuService::setMenu($params['appname'],$authInfo['data']['auth_id'], $params['content']);
        returnjson($data, $this->returnstyle,$this->callback);









    }

}