<?php
/**
 * 美味不用等的接口文档会文件更新在接口文档地址上
 * Created by PhpStorm.
 * User: zhangkaifeng
 * Date: 31/07/2017
 * Time: 18:42
 * 表：前缀_mweebookorder
 */

namespace Mwee\Controller;


use Common\Controller\CommonController;
use Mwee\Service\BookService;

class BookController extends CommonController
{
    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 4.1.1获取预订配置信息接口
     */
    public function bookdate()
    {
        $params['sid'] = I('post.sid');
        if (in_array('', $params)) {
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }
        $admininfo = $this->getMerchant($this->ukey);
        $sid = CommonMwee::poinumberToSid($params['sid'], $admininfo);
        if (false === $sid) {
            returnjson(array('code'=>102), $this->returnstyle, $this->callback);
        }
        $return = BookService::bookInfo($sid);
        returnjson($return, $this->returnstyle, $this->callback);
    }


    /**
     * 4.1.5 预订余量接口
     */
    public function bookidle()
    {
        $params['shopnumber'] = I('post.sid');
        $params['orderDate'] = I('post.timestamp');
        if (in_array('', $params)) {
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }
        $admininfo = $this->getMerchant($this->ukey);
        $sid = CommonMwee::poinumberToSid($params['shopnumber'], $admininfo);
        if (false === $sid) {
            returnjson(array('code'=>102), $this->returnstyle, $this->callback);
        }
        $params['orderDate'] = date('Ymd', $params['orderDate']);
        if ($params['orderDate']){
            $return = BookService::bookIdle($sid, $params['orderDate']);
            returnjson($return, $this->returnstyle, $this->callback);
        }else{
            returnjson(array('code'=>1051), $this->returnstyle, $this->callback);
        }

    }



    public function booksubmit()
    {
        $params['position'] = I('post.position');//预订位置(10:大厅;20: 包房优先;30:必须包房)
        $params['phone'] = I('post.phone');//预订人手机号
        $params['bookingTime']= I('time');//预订时间(毫秒级别)
        $params['status']=10;//订单状态:10 表示已确认、20 表示未处理、30 表示已就餐、40 表示 未就餐、50 已取消、 60 已删除、70 表示留坐 80、就餐中，90 商户拒绝
        $params['name']=I('post.name');//预订人姓名
        $params['peopleNumber']=I('post.number');//预订人数
        $params['gender']=I('post.gender');//预订人性别(10:女士，20: 先生)
        $params['updatedTime']= floor(microtime_float() * 1000);//当前时间
        $params['orderId']= 'book' . date('YmdHis') . rand(1000, 9999);//接入方的订单 id
        $params['vendorShopId']=I('post.sid');//厂商的商户 ID
        $params['apm']=I('post.apm');//预订市别 10:午市,20:晚 市
        $params['prepayAmount']=0;//预付定金,没有传 0

        if (in_array('', $params, true)) {
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }

        $admininfo = $this->getMerchant($this->ukey);
        $sid = CommonMwee::poinumberToSid($params['vendorShopId'], $admininfo);
        if (false === $sid) {
            returnjson(array('code'=>102), $this->returnstyle, $this->callback);
        }
        $params['vendorShopId'] = $sid;


        $return = BookService::bookSubmit($params, $admininfo);
        returnjson($return, $this->returnstyle, $this->callback);
    }



    /**
     * 4.1.3 预订状态查询接口
     */
    public function bookstatus()
    {
        $params['orderid'] = I('post.orderid');
        if (in_array('', $params)) {
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }
        $admininfo = $this->getMerchant($this->ukey);
        $return = BookService::bookStatus($params['orderid'], $admininfo);
        returnjson($return, $this->returnstyle, $this->callback);
    }


    /**
     * 按手机号查询订单
     */
    public function bookuserlist()
    {
        $params['phone'] = I('phone');
        $params['key_admin'] = I('key_admin');
        if (in_array('', $params)) {
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }
        $admininfo = $this->getMerchant($this->ukey);
        $db = M('mweebookorder', $admininfo['pre_table']);
        $sel = $db->where(array('phone'=>$params['phone']))->select();
        if (count($sel) > 0) {
            returnjson(array('code'=>200, 'data'=>$sel), $this->returnstyle, $this->callback);
        }else{
            returnjson(array('code'=>102), $this->returnstyle, $this->callback);
        }
    }














}