<?php
/**
 * Created by PhpStorm.
 * User: zhangkaifeng
 * Date: 20/07/2017
 * Time: 17:25
 * 需要用到的表：表前缀加mweegoodsorder，如：zhihuitu_mweegoodsorder
 */

namespace Mwee\Controller;


use Common\Controller\CommonController;
use Mwee\Service\GoodsMenuService;
use Mwee\Service\OrderService;

class MweeGoodsOrderController extends CommonController
{
    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 订餐，预点单对接
     * 此接口仅用post接收参数
     */
    public function Order()
    {
        $params=I('post.');
//        $post = '{
//    "items": [
//        {
//            "vendorDishId": "2901873",
//            "itemType": 1,
//            "dishName": "糯香辣排骨",
//            "description": "",
//            "price": 0.1,
//            "unit": "份",
//            "minChoose": 1,
//            "isHot": 0,
//            "isMarketPrice": 0,
//            "status": 1,
//            "quantity": 3,
//            "modifiers": [
//                {
//                    "modifierId": 201517,
//                    "type": 1,
//                    "price": 14.9,
//                    "name": "大份",
//                    "vendorDishId": "0",
//                    "isDefault": 0,
//                    "isSet": 0,
//                    "qty": 10,
//                    "unit": "",
//                    "picture": ""
//                },
//                {
//                    "modifierId": 201516,
//                    "type": 1,
//                    "price": 0,
//                    "name": "份",
//                    "vendorDishId": "0",
//                    "isDefault": 1,
//                    "isSet": 0,
//                    "qty": 13,
//                    "unit": "",
//                    "picture": ""
//                }
//            ]
//        },
//        {
//            "vendorDishId": "2901888",
//            "dishName": "石锅沃豆腐",
//            "itemType": "1",
//            "price": "0.01",
//            "minChoose": "0",
//            "isHot": "1",
//            "isMarketPrice": "1",
//            "status": "1",
//            "unit": "份",
//            "quantity": "3"
//        }
//    ],
//    "vendorShopId": "169195",
//    "tableNumber": "",
//    "totalPrice": "",
//    "contacts": "哈哈哈先生",
//    "mobile": "123646",
//    "createTime": "",
//    "note": "児",
//    "sid": "169195",
//    "people": "5",
//    "shopName": "店名",
//    "subtotal": "1000",
//    "comment": "评价",
//    "tablename": "tableName",
//    "key_admin": "202cb962ac59075b964b07152d234b70",
//    "userappid": 123456789
//}';
//        $params=json_decode($post, true);
        if (!$params['key_admin'] || !$this->userucid){
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }
        $admininfo = $this->getMerchant($params['key_admin']);

        $sid = CommonMwee::poinumberToSid($params['sid'], $admininfo);
        if (false === $sid) {
            returnjson(array('code'=>102), $this->returnstyle, $this->callback);
        }
        $params['sid'] = $sid;
        $params['vendorShopId'] = $sid;


        $return = OrderService::order($params, $admininfo, $this->userucid);
        returnjson($return, $this->returnstyle, $this->callback);
    }


    /**
     * 秒点提交（已暂停对接）
     */
    public function ordersubmit()
    {
        $params['key_admin'] = I('post.key_admin');
        $params['userucid'] = $this->userucid;
        $params['code'] = I('post.url');
        if (in_array('', $params)){
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }
        $admininfo = $this->getMerchant($params['key_admin']);

        $return = OrderService::submitOrder($params['code'], $params['userucid'], $admininfo);
        returnjson($return, $this->returnstyle, $this->callback);
    }


    /**
     * 订单列表
     */
    public function orderlist()
    {
        $admininfo = $this->getMerchant($this->ukey);
        $params['userucid'] = $this->userucid;//I('userid');
        if (in_array('', $params)) {
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }
        $db = M('mweegoodsorder', $admininfo['pre_table']);
        $sel = $db->where($params)->select();//->field('itemlists', true)
        if ($sel){
            returnjson(array('code'=>200, 'data'=>$sel), $this->returnstyle, $this->callback);
        }else{
            returnjson(array('code'=>102), $this->returnstyle, $this->callback);
        }
    }


    /**
     * 订单状态
     */
    public function orderstatus()
    {
        $params['orderId'] = I('ourorderid');
        $params['vendorShopId'] = I('sid');//美味不用等店铺id
        if (in_array('', $params)) {
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }
        $return = OrderService::orderStatus($params);
        returnjson($return, $this->returnstyle, $this->callback);
    }









}