<?php
/**
 * Created by PhpStorm.
 * User: zhangkaifeng
 * Date: 03/08/2017
 * Time: 19:52
 */

namespace Mwee\Controller;


use Common\Controller\CommonController;

class ShopInfoController extends CommonController
{
    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
    }

//    public function shopinfo()
//    {
//        $params['shopno'] = I('shopno');
//        if (in_array('', $params)) {
//            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
//        }
//
//        $array = array('mall_id'=>'51f9d9b831d65584ab000110', 'sign'=>'ttsx', 'shop_id'=>$params['shopno']);
//        $return = http('http://hdp.rongyi.com/api/shop/detail', $array, 'POST');
//        if (is_json($return)) {
//            $arr = json_decode($return, true);
//            if (0 == $arr['meta']['errno']) {
//                returnjson(array('code'=>200, 'data'=>$arr['result']), $this->returnstyle, $this->callback);
//            }else {
//                returnjson(array('code'=>104, 'data'=>$arr), $this->returnstyle, $this->callback);
//            }
//        }else{
//            returnjson(array('code'=>101), $this->returnstyle, $this->callback);
//        }
//    }


    public function shopinfo()
    {
        $admininfo = $this->getMerchant($this->ukey);
        $params['poinumber'] = I('poinumber');
        $params['idtype'] = I('idtype');
        if (in_array('', $params, true)) {
            returnjson(array('code'=>1030), $this->returnstyle, $this->callback);
        }
        //idtype类型：0为品牌导览店铺id，1为美味不用等店铺id，所以如果传1，需要查出拼花导览店铺id
        if ($params['idtype'] == 1){
            $db = M('total_mwee_shopid');
            $select = $db->field('sid,shopnumber')->where(array('sid'=>array('in', $params['poinumber'])))->select();
            $params['poinumber'] = array_column($select, 'shopnumber');
        }


        $buildid = I('buildid');
        if (!$buildid) {
            $builddb = M('total_buildid');
            $buildid = $builddb->where(array('adminid'=>$admininfo['id']))->select();
            if (!$buildid) {
                returnjson(array('code'=>102, 'data'=>1), $this->returnstyle, $this->callback);
            }
            if (count($buildid) > 1 ){
                returnjson(array('code'=>107), $this->returnstyle, $this->callback);
            }
            $buildid = $buildid[0]['buildid'];
        }

        $db = M($admininfo['pre_table'] . 'map_poi_' . $buildid, '', 'DB_CONFIG2');
        $find = $db->field('poi_number,poi_image,poi_name,poi_logo,banner')->where(array('poi_number'=>array('in', $params['poinumber'])))->select();
        if ($find){
            foreach ($select as $key => $value) {
                foreach ($find as $k => $v) {
                    if ($v['poi_number'] == $value['shopnumber']) {
                        $find[$k]['mwsid'] = $value['sid'];
                        continue;
                    }
                }
            }
            returnjson(array('code'=>200, 'data'=>$find), $this->returnstyle, $this->callback);
        }else{
            returnjson(array('code'=>102), $this->returnstyle, $this->callback);
        }

    }








}