<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 19/12/2017
 * Time: 10:27
 */

namespace EnterpriseWechat\Controller\App\Message;


use Common\Controller\CommonController;
use EnterpriseWechat\Service\Message\SendMessageService;
use EnterpriseWechat\Service\Open\AppInfoService;

class SendMessageController extends CommonController
{

    public function _initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
    }

    public function sendMessage()
    {
        $params['appname'] = I('get.appname');
        $params['timestamp'] = I('get.timestamp');
        $params['sign'] = I('get.sign');
        $params['key_admin'] = I('get.key_admin');
        $params['content'] = file_get_contents('php://input');
        if (in_array('', $params)){
            returnjson(['code'=>1030],$this->returnstyle,$this->callback);
        }

        $content = $params['content'];
        $sign = $params['sign'];
        unset($params['content']);
        unset($params['sign']);
        $ct=time()-$params['timestamp'];
        //如果计算得出来的秒数大于正负60秒，则判定请求方的服务器时间不对
        if ($ct > 60 || $ct < -60){
            returnjson(['code'=>1056], $this->returnstyle, $this->callback);
        }


        $adminInfo = $this->getMerchant($params['key_admin']);
        $params['sign_key'] = $adminInfo['signkey'];
        if (sign($params) != $sign){//签名不对
            returnjson(['code'=>1002],$this->returnstyle,$this->callback);
        }

        $authInfo = AppInfoService::getRelationShip($adminInfo, $params['appname']);
        if (!is_array($authInfo) || $authInfo['data']['auth_id'] == false){
            returnjson($authInfo, $this->returnstyle, $this->callback);
        }





        $data = SendMessageService::sendMessage($params['appname'], $authInfo['data']['auth_id'], $content);

        returnjson($data, $this->returnstyle,$this->callback);









    }

}